local ui = require('harpoon.ui')

vim.cmd([[autocmd BufReadPost * lua require('harpoon.mark').add_file()]])
vim.keymap.set("n", "<C-o>", ui.toggle_quick_menu)
vim.keymap.set("n", "<Tab>", function() ui.nav_next() end)
vim.keymap.set("n", "<C-Tab>", function() ui.nav_prev() end)
vim.keymap.set("n", "<C-1>", function() ui.nav_file(1) end)
vim.keymap.set("n", "<C-2>", function() ui.nav_file(2) end)
vim.keymap.set("n", "<C-3>", function() ui.nav_file(3) end)
vim.keymap.set("n", "<C-4>", function() ui.nav_file(5) end)
